name: Deploy to GH Pages

on:
  push:
    branches: -main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v3
      - name: Setup Node.js
        uses: action/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependecies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
